### PR TITLE
Sync latest datadog release

### PR DESCRIPTION
**Pull request by venku122**
Updates our buildpack the the latest releases, while preserving our custom changes.

### CODE REVIEW

**Comment by marcusmolchany** [comment]
who should review this? all it was was taking in the latest commits from the datadog repo into ours

**Comment by venku122** [comment]
@marcusmolchany Talked with @jshanman a bit this morning.

Looks like our custom config changes are no longer necessary. Payments uses the mainline build pack already. Justin will swap this out for the mainline version on baron-dev and baron-prod and add the required env vars.

**Comment by cjhin** [comment]
@venku122 we can close this PR right? (trying to close out my github notifications)

**Comment by venku122** [comment]
Yes

**Pull request closed without merging**
